### ISSUE TITLE
[Login] OAuth Application API is Deprecating 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#1834] opened 2020-03-04 18:20 UTC
[OAuth Application API is Depreciating](https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/). We need to move to the new endpoint by July 1st

**Comment by KyleJu** [comment] 2020-03-04 18:25
Plan to tackle it in Q2 as a P1.

**Comment by KyleJu** [comment] 2020-04-15 00:50
This issue has been resolved in #1839.

GitHub is replacing `GET /applications/:client_id/tokens/:access_token` with `POST /applications/:client_id/token`, which affects https://github.com/web-platform-tests/wpt.fyi/blob/111641e0cefbfee98cda2c83a7ba360bf7d31668/shared/github_oauth.go#L151. However the underlying [go-github library](https://github.com/google/go-github) has implemented [this change](https://github.com/google/go-github/issues/1331) and included in release [v29.0.3](https://github.com/google/go-github/compare/v29.0.3...master).

There is no breaking changes in the [implementation](https://github.com/google/go-github/pull/1461/files#diff-fa118b5047b081bf147238afc4f38b36R146) and hence this issue is resolved.

**Comment by KyleJu** [comment] 2020-04-15 00:54
@LukeZielinski

**Comment by Hexcles** [comment] 2020-04-15 15:17
> On April 14th, 2020 at 08:38 (PDT), your application (wpt-metadata (staging)) issued a request using the deprecated form of OAuth Application API that includes access tokens in the URL path. GitHub has deprecated these endpoints and replaced them with a version that accepts access tokens in the request body.

I wonder what is still using this API then? #1839 landed in March.

**Comment by LukeZielinski** [comment] 2020-04-15 15:22
@Hexcles Where is that message coming from? Logs? Email?

**Comment by Hexcles** [comment] 2020-04-15 15:26
That was from an email from GitHub (delivered to my chromium.org account and I'm not quite sure why -- maybe I registered this GitHub OAuth application originally).

I did a little digging. This is the change we want: https://github.com/google/go-github/commit/419f07c399bbced679719c419ae683618018556c And it's in v31 according to the tag.

@KyleJu could you try rolling `go-github` to v31? Note that according to the [release logs](https://github.com/google/go-github/releases) there might be some breaking changes.

**Comment by Hexcles** [comment] 2020-04-15 15:31
I think the confusion here was caused by a misunderstanding in the [revision selection](https://git-scm.com/docs/gitrevisions) syntax of git.

The link you quoted (https://github.com/google/go-github/compare/v29.0.3...master) included changes **from** v29.0.3, not **until**, so seeing the change we want in that list means we don't have that change.

**Comment by KyleJu** [comment] 2020-04-15 17:17
@Hexcles Indeed I read it wrong. Thanks for pointing it out.

Here are the changes from [v29.03 to v31](https://github.com/google/go-github/compare/v29.0.3...v31.0.0). There are a few other breaking changes but I still don't think it would break ours since we don't use these APIs. Hopefully by upgrading to v31, everything will work as it is.

**Closed** 2020-04-17 18:23 UTC
