### ISSUE TITLE
.any.js tests that run in jsshell generate extra .any.js entries in the dashboard

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt.fyi#2332] opened 2021-01-05 20:34 UTC
Take a look at https://wpt.fyi/results/streams?label=experimental&label=master&aligned and notice the existence of `queuing-strategies.any.js`. There is no such row for `idlharness.any`, though.

I'm pretty sure this is due to the line

```js
// META: global=window,worker,jsshell
```

in https://github.com/web-platform-tests/wpt/blob/d3ce095fcc6b5a85e6056fdebbf939caf2e2719f/streams/queuing-strategies.any.js

i.e. the existence of the unusual "jsshell" environment causes this extra line.

**Comment by stephenmcgruer** [comment] 2021-01-08 18:58
Thanks for the report!

Appears to be a duplicate of https://github.com/web-platform-tests/wpt.fyi/issues/1469

**Closed** 2021-01-08 18:58 UTC
Labels: duplicate
