### ISSUE TITLE
Duplicate Safari runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1285] opened 2019-04-29 08:18 UTC
https://wpt.fyi/runs now shows this:
![image](https://user-images.githubusercontent.com/498917/56883618-82ca9100-6a67-11e9-8a58-11e0bbbc1033.png)

301ce26 has 5 copies of each Safari configuration from Azure Pipelines. d3cf77a appears to be when duplication started.

For 301ce26 the source build was https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14126 and it looks like the wpt.fyi hook was only invoked once per configuration, and I see exactly two hits for "api/checks/azure/14126" in GCP logs.

This suggests a duplication bug in the results receiver. @Hexcles can you take a look?

**Comment by Hexcles** [comment] 2019-05-01 15:26
I downloaded a few of the many "duplicate" runs and they are all different: slightly different timestamps and different results from the same commit (because of flaky tests) suggest that there were a few Azure builds triggered from this same commit.

I don't know how to find *all* the Azure builds for a particular commit; the search feature on the Azure UI doesn't seem to do what I want. Only the latest Azure build can be found via GitHub Checks: 
https://github.com/web-platform-tests/wpt/runs/113332481
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14126&view=logs 

A few jobs were mysteriously abandoned, which might suggest something funny was going on.

At least I'm fairly certain that this is not a regression or a bug in the results receiver, so I'm passing back to you in case you want to look into the Azure failures (though I think it's fairly low-priority unless it happens again) @foolip .

**Comment by foolip** [comment] 2019-05-03 10:38
I clicked "Show more" many, many times and scrolled back to when this occurred. You're right, there were multiple scheduled builds:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14110
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14112
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14113
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14118
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14120
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14122

@thejohnjansen @mustjab is there something we can do to understand why there were six scheduled builds instead of one here? We have "Only schedule builds if the source or pipeline has changed" check in our triggers for this so that this sort of duplication doesn't happen.

Aside: there were also CI builds triggered by branch updates but they (correctly) didn't run the tests:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14106
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14107
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14111
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14117

@Hexcles is this sort of accidental duplication something you could include in the results validation work? I'm not sure if it's worth deleting the dupes, but it's still an infra bug we should take action on.

**Comment by Hexcles** [comment] 2019-06-20 14:47
Closing this as a duplicate of #1151 .

**Closed by Hexcles** 2019-06-20 14:47 UTC
Labels: bug
