### ISSUE TITLE
Expose results for experimental browsers in a way that is easily linked

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#60] opened 2018-04-17 09:32 UTC
This is the frontend part of https://github.com/web-platform-tests/results-collection/issues/146.

@lukebjerring has suggested we could use a label system to be able to mix-and-match. Anything that will allow us to have one link for Chrome+Edge+Firefox+Safari stable, and another for their most recent pre-stable builds, would do the job.

**Comment by foolip** [comment] 2018-04-17 09:38
Issues for getting experimental results:
* [Chrome + Firefox](https://github.com/w3c/web-platform-tests/pull/9226) on Taskcluster
* [Chrome Dev](https://github.com/web-platform-tests/results-collection/issues/388)
* [Edge Insider Preview](https://github.com/web-platform-tests/results-collection/issues/109)
* [Firefox Nightly](https://github.com/web-platform-tests/results-collection/issues/521)
* [Safari Technology Preview](https://github.com/web-platform-tests/results-collection/issues/112)

**Comment by jugglinmike** [comment] 2018-04-17 15:57
Results for experimental builds of Chrome and Firefox are now available in the same format/location as the results for stable builds.

**Comment by foolip** [comment] 2018-04-17 16:06
@jugglinmike, are the unsplit wptreport JSON files also preserved somewhere?

**Comment by jugglinmike** [comment] 2018-04-17 17:02
Nope. We can start doing this if you like, but storing the complete WPT report is part of @Hexcles' [proposal for the results receiver](https://docs.google.com/document/d/1F3GWJ6lA8C3S5WgyJgXxmTFzu92mqF-1ddGije67ork). Unless there is some specific value in the unsplit files themselves (and depending on how much time Robert will need), it might be wise to wait for the new results receiver.

**Comment by foolip** [comment] 2018-04-17 19:25
Nah, if you don't happen to have it then let's treat it like all other results and transition by re-merging them.

**Comment by lukebjerring** [comment] 2018-04-23 21:15
I'm going to do this in a few steps.
First up, I'll add `?label=unstable` but spoof it under the hood to change the browser names to `[name]-experimental` during the query, and we'll set that sit in staging until `results-receiver` progresses.

**Comment by foolip** [comment] 2018-07-23 09:36
@orphis asked me about experimental runs on wpt.fyi today and I pointed him at https://wpt.fyi/results/?label=experimental.

@lukebjerring, is all that remains of this issue to make experimental runs more discoverable?

**Comment by lukebjerring** [comment] 2018-10-04 14:02
Closing this as a dupe of #379, which will be fixed via https://github.com/web-platform-tests/wpt.fyi/issues/535

**Closed by lukebjerring** 2018-10-04 14:02 UTC

**Comment by foolip** [comment] 2018-10-04 16:28
There is something left beyond https://github.com/web-platform-tests/wpt.fyi/issues/535, which is to make it *easy* to discover that ?label=experimental is a useful view, which isn't quite the same as the ability to pick an arbitrary set of runs.
