### ISSUE TITLE
Spaces in search queries turn into plus symbols after URL roundtrip

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1418] opened 2019-08-16 04:28 UTC
Repro steps:
- Start at https://wpt.fyi/results/?run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004
- Paste `seq(status:pass status:!pass status:pass status:!pass)` into the search box and submit
- The URL will change to https://wpt.fyi/results/?q=seq%28status%3Apass%2Bstatus%3A%21pass%2Bstatus%3Apass%2Bstatus%3A%21pass%29&run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004
- Open the same URL in a new tab
- Observe `seq(status:pass+status:!pass+status:pass+status:!pass)` in the query, which does't work.

Looks like there's one layer too much of escaping. `+` does encode a space in URLs in some context, and that's been encoded into `%2B` in turn.

**Comment by foolip** [comment] 2019-08-16 04:32
One can manually fix the URL by replacing `%2B` with `%20`:
https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3A%21pass%20status%3Apass%20status%3A%21pass%29&run_id=274960001&run_id=280900008&run_id=271190001&run_id=284730004

Loading it then works, but the URL is rewritten immediately so it can't be copied.

**Comment by lukebjerring** [comment] 2019-08-16 11:41
Duplicate of https://github.com/web-platform-tests/wpt.fyi/issues/1375

**Closed by lukebjerring** 2019-08-16 11:41 UTC
Labels: bug
