### ISSUE TITLE
Error 500: Unable to triage metadata

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1885] opened 2020-04-10 18:30 UTC
Starting at https://wpt.fyi/results/custom-elements?label=experimental&label=master&aligned, I clicked the table cell saying "149 / 441" for builtin-coverage.html on Safari. Trying to link https://bugs.webkit.org/show_bug.cgi?id=182671 I got the error "500: Unable to triage metadata: POST https://api.github.com/repos/web-platform-tests/wpt-metadata/git/commits: 422 Validation Failed [{Resource:author Field:email Code:missing_field Message:}]"

Screenshots:

<img width="1135" alt="Screen Shot 2020-04-10 at 20 25 55" src="https://user-images.githubusercontent.com/498917/79013856-ead79180-7b69-11ea-8a5c-507ad658fee6.png">

<img width="1135" alt="Screen Shot 2020-04-10 at 20 26 00" src="https://user-images.githubusercontent.com/498917/79013863-f034dc00-7b69-11ea-83e0-2f9a80ff5c19.png">

**Comment by foolip** [comment] 2020-04-14 14:12
I got the same error now trying to triage some failures to https://bugs.webkit.org/show_bug.cgi?id=176454, which suggests it wasn't a fluke but will be a persistent problem.

**Comment by KyleJu** [comment] 2020-04-14 15:27
Cannot reproduce using my GitHub account, https://github.com/web-platform-tests/wpt-metadata/pull/145. I suspect an issue with calling [commit API](https://developer.github.com/v3/git/commits/#create-a-commit). Digging more

**Comment by KyleJu** [comment] 2020-04-14 15:40
duplicate of #1863

**Closed** 2020-04-14 16:30 UTC
Labels: bug, prod

**Comment by KyleJu** [comment] 2020-04-14 19:33
https://github.com/web-platform-tests/wpt.fyi/issues/1891 should fix this in prod now
