### ISSUE TITLE
Multi-tests should produce separate anchors in the summary page, and should be exposed as separate tests in the manifest (or something like it)

### ISSUE THREAD

**Issue by tabatkins** [web-platform-tests/wpt.fyi#270] opened 2018-06-13 22:45 UTC
Test files that contain a single test, like most CSS tests, map easily to things I can put into `<wpt>` elements and track inline in a spec.

But many specs instead use large JS test files with many individual tests in them, like https://wpt.fyi/results/dom/historical.html. These do *not* map well. But they are clearly individually addressable in the system, since that page lists them all individually.

There should be some discoverable anchor associated with each of them, so people can address them in a `<wpt>` element (like `dom/historical.html#DOMCursor` or something) and I can link to wpt.fyi and have it hit that particular subtest.

**Comment by lukebjerring** [comment] 2019-09-17 02:25
I believe that parameterized tests are separated in the manifest (we check the separate test names are listed in the manifest to verify/test [wpt-metadata](https://github.com/web-platform-tests/wpt-metadata/blob/a995adf99bb35b931408553f59d5d59b8d52df53/html/dom/META.yml#L5), for example).

However, I'm interpreting this as needing subtest permalinking, so closing as a dupe of https://github.com/web-platform-tests/wpt.fyi/issues/464

**Closed by lukebjerring** 2019-09-17 02:25 UTC
