### ISSUE TITLE
Sort out the "complete" API parameter and its interaction with the frontend

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#468] opened 2018-08-23 08:53 UTC
https://wpt.fyi/api/runs?complete=true does something different from https://wpt.fyi/api/runs but it is not documented in https://github.com/web-platform-tests/wpt.fyi/blob/master/api/README.md

**Comment by lukebjerring** [comment] 2018-08-23 09:39
Not sure if there's an open issue for it, but the definition of complete actually needs addressing / changing as well as documentation.

`complete` should only be used when `sha` is `latest`, and should mean "the most recent run that contains all of the products in the query". Currently though, it is implemented as "the most recent run that contains all of the default products". These two definitions have the same meaning when the query does not contain specific products (and uses the default product set).

**Comment by Hexcles** [comment] 2018-08-24 19:01
I just discussed offline with @mdittmer . The problem is multifaceted:

* The "complete" parameter of `/api/runs` is a bit confusing as said above. We need to document its behaviour or even rework the parameter to better suit use cases (speaking of that, we should revisit the use case and intention).
* The frontend currently doesn't know about the "complete" parameter, which prevents it from applying more advanced logic related to the parameter.
     * Background: The parsing and deserialization of query parameters happen on the server side. Go code then fills the param struct back into Go templates to pass the parameters as properties to web components. Yet currently the web component doesn't have a "complete" parameter.
     * A demonstration of this problem is that adding `?complete=true` or `?complete=false` to front-end URLs doesn't do anything.

Mark and I think we should use a simple hack to provide a somewhat natural user experience so that we can make a prod release next week. After that, we can think about how to fix the issue properly.

**Comment by lukebjerring** [comment] 2018-08-30 21:11
> rework the parameter to better suit use cases

Addressed by #491 

> The frontend currently doesn't know about the "complete" parameter, 

Addressed by #498

Additional problems:
- `complete` has no effect in /interop (addressed by #488)
- `products` is always "chrome","edge","firefox","safari" (addressed by #491)
- `GetCompleteSHAs` implementation ignores labels (addressed by #491)

We're in a healthier state after those PRs land, by which stage we'll confirm expectations/use-cases, and document things

**Comment by lukebjerring** [comment] 2018-09-27 16:53
#532 renamed `complete` to `aligned`,  better reflecting it's meaning.

**Closed** 2018-09-27 16:58 UTC

**Comment by foolip** [comment] 2018-09-28 12:16
Thanks Luke, that makes a lot more sense!
