### ISSUE TITLE
Search results are returning 404s

### ISSUE THREAD

**Issue by progers** [web-platform-tests/wpt.fyi#1727] opened 2020-01-06 16:41 UTC
Some search results are failing with 404. [Here](https://wpt.fyi/results/?label=master&product=chrome&product=edge&product=firefox&product=safari&product=servo&product=webkitgtk&q=%28chrome%3A%21pass%26chrome%3A%21ok%29%20%28edge%3Apass%7Cedge%3Aok%29%20%28firefox%3Apass%7Cfirefox%3Aok%29%20%28safari%3Apass%7Csafari%3Aok%29%20%28servo%3Apass%7Cservo%3Aok%29%20%28webkitgtk%3Apass%7Cwebkitgtk%3Aok%29) is an example url (linked from https://wpt.fyi/insights).

**Comment by KyleJu** [comment] 2020-01-06 16:49
Search queries seem to be failing due to (servo:pass|servo:ok). Any combination without it works properly

**Comment by stephenmcgruer** [comment] 2020-01-09 18:14
@Hexcles can you own this?

**Comment by KyleJu** [comment] 2020-01-09 18:26
Note that the same query works on [staging](https://staging.wpt.fyi/insights)

**Comment by Hexcles** [comment] 2020-01-10 18:39
This is caused by skipping searchcache in the previous prod push (#1717).

Unfortunately, it's not possible to redeploy searchcache at da11a4d; we need #1734 . I'm going to do a new prod push instead.

**Comment by Hexcles** [comment] 2020-01-10 20:28
Fixed by #1736 .

**Closed by Hexcles** 2020-01-10 20:28 UTC
