### ISSUE TITLE
web_components_test & go_chrome_test flakiness

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2985] opened 2022-09-30 20:11 UTC
web_components_test & go_chrome_test are both experiencing flakiness and the issue lies in downloading the Chrome Stable build:

```
if [[ -z "$(which google-chrome)" ]]; then \
	ARCHIVE=google-chrome-stable_current_amd64.deb; \
	wget -q https://dl.google.com/linux/direct/${ARCHIVE}; \
	sudo dpkg --install ${ARCHIVE} 2>/dev/null || true; \
	sudo apt-get install --fix-broken -qqy; \
	sudo dpkg --install ${ARCHIVE} 2>/dev/null; \
fi
Selecting previously unselected package google-chrome-stable.
(Reading database ... 104859 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable ([106](https://github.com/web-platform-tests/wpt.fyi/actions/runs/3147582963/jobs/5146415715#step:3:107).0.5249.91-1) ...
Processing triggers for mime-support (3.62) ...
E: Failed to fetch http://deb.debian.org/debian/pool/main/libn/libnet-ssleay-perl/libnet-ssleay-perl_1.85-2+b1_amd64.deb  404  Not Found [IP: 146.75.106.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
(Reading database ... 104974 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (106.0.5249.91-1) over (106.0.5249.91-1) ...
Processing triggers for mime-support (3.62) ...
make: *** [Makefile:[118](https://github.com/web-platform-tests/wpt.fyi/actions/runs/3147582963/jobs/5146415715#step:3:119): chrome] Error 1
```

**Comment by DanielRyanSmith** [comment] 2022-09-30 20:55
While investigating this issue, it might also be worth investigating a previously existent flaky test case that appears during browser testing. I'll look to see if I can find an example of this, but a flaky scenario that has existed for some time involves an error along the lines of `Error thrown outside of test function`. It is something that has occurred rarely for as some months, and is likely an async issue somewhere in the testing code.

**Comment by past** [comment] 2022-10-01 01:51
The specific version of libnet-ssleay-perl that the scipt is looking for is indeed [missing](http://deb.debian.org/debian/pool/main/libn/libnet-ssleay-perl/libnet-ssleay-perl_1.85-2+b1_amd64.deb). I can't reproduce locally since my development docker image ends up with version 1.85-2+deb10u1 which does [exist](https://deb.debian.org/debian/pool/main/libn/libnet-ssleay-perl/libnet-ssleay-perl_1.85-2+deb10u1_amd64.deb). The b1 versions [seem](https://www.debian.org/doc/manuals/developers-reference/pkgs.html#recompilation-or-binary-only-nmu) to be not what we normally want and crucially are not available [for every version](https://deb.debian.org/debian/pool/main/libn/libnet-ssleay-perl/).

Hopefully the change in #2987 fixes this and we don't have to dig further.

**Comment by jcscottiii** [comment] 2022-10-03 14:31
I *think* that the index of package locations is stale sometimes. That is why it fails with the 404.

Adding `sudo apt-get update` might help.

I tried it in #2992 but cannot guarantee that it solved the actual problem.

**Comment by past** [comment] 2022-10-03 22:13
The 404 isn't transient, if you look at the [package directory](https://deb.debian.org/debian/pool/main/libn/libnet-ssleay-perl/), but maybe you are saying that package resolution takes the index into account at one point and _that_ lookup fails? I don't know a lot about Debian's package resolution and where that index resides.

**Comment by past** [comment] 2022-11-01 20:25
This hasn't occurred again recently, so I'll close it for now, but feel free to reopen if it surfaces again.

**Closed by past** 2022-11-01 20:25 UTC
