### ISSUE TITLE
"Cannot identify uploader" on https://staging.wpt.fyi/api/results/upload

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1108] opened 2019-02-01 12:49 UTC
Even though I have filled in uploader (foolip) I'm getting the error "Cannot identify uploader" when trying to upload.

The error is from here:
https://github.com/web-platform-tests/wpt.fyi/blob/ca1df6914d221b71442a265dfca23f72e2110b4b/api/receiver/receive_results.go#L57

This worked yesterday and the code looks very simple, so I don't have any ideas about what might have caused it.

**Comment by lukebjerring** [comment] 2019-02-01 13:17
This is not likely to be a regression, since this code hasn't change in the last week and we have pushed to prod yesterday.

More likely is that you used the html form with an administrative account, which bypasses the need for the uploader credentials to be present on the request. Are you making the next upload request in a different way?

**Comment by foolip** [comment] 2019-02-01 21:19
The only difference I can think of is that I'm trying to upload multiple files. When it worked I also filled out the uploader, at least I think so. Should it not be necessary? I

I'm also not entirely sure what account I'm logged in with, presumably this matters? There's no UI to change it or log out, so I just don't know.

**Comment by lukebjerring** [comment] 2019-02-01 21:35
I believe it's whatever google account you're using.

**Comment by foolip** [comment] 2019-02-01 23:07
I'm logged into many accounts. Is there a way to log out of wpt.fyi so that I have to chose again? And does it matter at all for this issue?

**Comment by foolip** [comment] 2019-02-02 09:32
It works in an incognito window after I log in with google.com account. So it probably has something to do with auth. How can I debug to help resolve this?

**Comment by Hexcles** [comment] 2019-02-12 22:42
I suspect you somehow logged into wpt.fyi with your non-corp account. Only your corp account is in the GCP project. I don't know how to switch accounts other than deleting your cookies on wpt.fyi.

**Comment by Hexcles** [comment] 2019-02-14 02:41
Tentatively closing unless it's not a multi-account issue.

**Closed by Hexcles** 2019-02-14 02:41 UTC
Labels: regression
