### ISSUE TITLE
Comparing stable to beta broken on staging.wpt.fyi

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#750] opened 2018-11-13 10:40 UTC
Same URL for staging and prod:
https://wpt.fyi/results/?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned
https://staging.wpt.fyi/results/?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned

The staging link says "Failed to fetch test runs", which seems to be because of the difference here:
https://wpt.fyi/api/runs?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned
https://staging.wpt.fyi/api/runs?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned

Staging doesn't return any aligned runs.

**Comment by lukebjerring** [comment] 2018-11-14 21:19
Duplicate of https://github.com/web-platform-tests/wpt.fyi/issues/755

**Closed by lukebjerring** 2018-11-14 21:19 UTC
Labels: regression
