### ISSUE TITLE
Generating list of Chrome-only failures via insights always includes WebKitGTK

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2246] opened 2020-11-09 09:03 UTC
This is what https://wpt.fyi/insights initially looks like:
![image](https://user-images.githubusercontent.com/498917/98520471-602b5200-2272-11eb-9c32-e231fb1b45f6.png)

If one unchecks Edge, Servo and WebKitGTK, WebKitGTK is still left in the query:
![image](https://user-images.githubusercontent.com/498917/98520528-7507e580-2272-11eb-8035-2aa9cb64d42c.png)

([Resulting URL](https://wpt.fyi/results/?label=master&product=chrome&product=firefox&product=safari&product=webkitgtk&q=%28chrome%3A%21pass%26chrome%3A%21ok%29%20%28firefox%3Apass%7Cfirefox%3Aok%29%20%28safari%3Apass%7Csafari%3Aok%29%20%28webkitgtk%3Apass%7Cwebkitgtk%3Aok%29))

This is a regression from adding WebKitGTK to wpt.fyi.

This is how people would generate a list of Chrome-only failures, so it's important that this works.

**Comment by Hexcles** [comment] 2020-11-11 18:54
Duplicate of #1878

**Closed by Hexcles** 2020-11-11 18:54 UTC
Labels: bug, regression
