### ISSUE TITLE
Show History sometimes failing

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#2111] opened 2020-08-17 15:34 UTC
Clicking "Show History" on [this](https://wpt.fyi/results/svg/animations?q=is%3Adifferent&run_id=636620001&run_id=648200002&run_id=655990003&run_id=619750003&run_id=642250001&run_id=651930002&run_id=634920003&run_id=638580001&run_id=644400001&run_id=627090004) view currently results in "Error: Row 0 is not null or an array." rather than any history

**Comment by foolip** [comment] 2022-05-10 20:44
This seems to happen when requesting the history for a directory as opposed to a specific test. @gsnedders do you have a use case for that, or would a good fix be remove the button when it won't work?

**Comment by past** [comment] 2023-02-17 18:01
I believe this was fixed by #2866 since I can no longer reproduce it.

**Closed by past** 2023-02-17 18:01 UTC
Labels: bug, front-end
