### ISSUE TITLE
Many runs with the same `raw_results_url`

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#738] opened 2018-11-08 12:50 UTC
Try this in JS:
```js
let runs = await (await fetch('https://wpt.fyi/api/runs?max-count=500')).json();
let uniqueResults = new Set(runs.map(run => run.raw_results_url));
console.log(runs.length, uniqueResults.size);
```

Right now this prints `1587 1557`, i.e. there are a number of runs that have the same `raw_results_url` as some other. `Array.from(uniqueResults).map(url => runs.filter(r => r.raw_results_url === url)).filter(runs => runs.length !== 1)` will list some.

An few examples extracted from that:
https://wpt.fyi/runs?sha=032cd9cc63 (dupe Chrome Dev from Nov 6, 2018)
https://wpt.fyi/runs?sha=e511e5e8af (dupe Safari and possible others from Aug 2017)

@Hexcles, ideas? Given how long back it goes it's not because of the results receiver, but it is still happening.

**Comment by Hexcles** [comment] 2018-11-09 21:03
#746 should prevent new duplicate runs from being created.

I could audit the existing duplication if you think it'd be helpful. Otherwise, let's close this issue (as dupe of #247 ).

**Comment by foolip** [comment] 2018-11-09 21:46
Deleting all runs (except one) with identical reports would be helpful, as it's logic that otherwise everyone working with the data has to discover the need for and implement. Before me, @s3ththompson also ran into it.

**Comment by Hexcles** [comment] 2018-11-14 23:35
The problem is in fact much worse than you said (perhaps because you only listed up to 500 runs per product, and/or some other implementation details of the query).

I did a full table scan of the test runs. In prod, we have 235 *groups* of duplication; 387 runs can be deleted (only preserve one run per group).

The number is a bit scary but I double checked my script and spot checked the duplicate entries. Many of the duplicate runs are in fact from a long time ago, long before the results receiver.

I'm pretty certain that the duplicate runs can be safely deleted as all the fields except timestamps are identical, but I've also backed up the whole TestRun table into gs://wptdashboard.appspot.com just in case.

**Closed** 2018-11-14 23:37 UTC

**Comment by Hexcles** [comment] 2018-11-14 23:46
In case my comment above wasn't clear:

I've run the script on both staging and prod and removed all the duplicate runs.

**Comment by foolip** [comment] 2018-11-15 21:45
Thanks @Hexcles!

> I did a full table scan of the test runs

How can I do this too? Sounds like https://github.com/web-platform-tests/wpt.fyi/issues/636 :)

**Comment by Hexcles** [comment] 2018-11-15 23:02
@foolip unfortunately that'd require you to authenticate and connect directly to Datastore. @lukebjerring will add proper pagination to the APIs to allow external users to do it.
