### ISSUE TITLE
"View source on GitHub" link doesn't work for synthetic tests

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt.fyi#1185] opened 2019-02-28 08:05 UTC
FOr example, https://wpt.fyi/results/webstorage/symbol-props.window.html links to https://github.com/web-platform-tests/wpt/blob/master/webstorage/symbol-props.window.html, which doesn't exist.

**Comment by lukebjerring** [comment] 2019-02-28 14:03
Is there a relevant source file that we should be pointing to instead?

**Comment by Ms2ger** [comment] 2019-02-28 14:09
Yeah, https://github.com/web-platform-tests/wpt/blob/master/webstorage/symbol-props.window.js.

There's a couple of these: v

**Comment by lukebjerring** [comment] 2019-02-28 14:15
Oh; I thought "synthetic tests" was another case other than one I've already covered.

- Head to wpt.fyi/flags
- Enable the feature `Fetch a manifest for a complete (expected) list of tests.` (and the sub-features)

That will fetch a relevant manifest and detect the fact that the source file is different than the test name.

**Comment by stephenmcgruer** [comment] 2020-01-28 14:24
Dupe of https://github.com/web-platform-tests/wpt.fyi/issues/1476

**Closed by stephenmcgruer** 2020-01-28 14:24 UTC
