### ISSUE TITLE
Duplicate checks (wpt.fyi and staging.wpt.fyi)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1047] opened 2019-01-20 22:21 UTC
### Check
A link to the GitHub Check run containing my issue:
https://github.com/web-platform-tests/wpt/pull/14952 lists these checks:
<img width="773" alt="screen shot 2019-01-20 at 11 20 20 pm" src="https://user-images.githubusercontent.com/498917/51445835-01e25780-1d0a-11e9-8381-cfb609bc98c4.png">

The first two "chrome[experimental]" are:
https://github.com/web-platform-tests/wpt/pull/14952/checks?check_run_id=52101574
https://github.com/web-platform-tests/wpt/pull/14952/checks?check_run_id=52102304

### Description

There's no indication that one of these is a staging check, they look the same in the PR view.

**Comment by lukebjerring** [comment] 2019-01-20 22:46
This is working as intended; The staging instance will be uninstalled (or, reduced to a small set of users) once the production instance has been verified. Only a small whitelist are seeing both at the moment.

**Comment by foolip** [comment] 2019-01-21 13:02
Can you make the description say "staging.wpt.fyi" instead to make it easier to spot this?

**Comment by Hexcles** [comment] 2019-03-14 22:21
Fixed by #1148 .

**Closed by Hexcles** 2019-03-14 22:21 UTC
Labels: bug
