### ISSUE TITLE
Use the earliest run when a product spec matches multiple runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#731] opened 2018-11-07 13:13 UTC
I had shared this link with @henbos showing improvements from https://github.com/web-platform-tests/wpt/pull/13795:
https://wpt.fyi/results/?product=chrome%40cf0adc7f3d&product=chrome%40ced8eec6f1&diff

However, the view changed after I shared the link. Adding `label=taskcluster` shows what I wanted to share as a stable link:
https://wpt.fyi/results/?label=taskcluster&product=chrome%40cf0adc7f3d&product=chrome%40ced8eec6f1&diff

The problem is that a Buildbot run arrived for cf0adc7f3d after I got the link, and we use the latest run in that situation. If we use the earliest run, then links like the one I shared would be stable.

**Comment by lukebjerring** [comment] 2019-01-08 16:15
I don't think this is what we want to do. We should instead be providing a `run_id` based permalink; Thus this is a dupe of #645

**Closed by lukebjerring** 2019-01-08 16:15 UTC
