### ISSUE TITLE
Wrong browser triaged after deleting a column

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1896] opened 2020-04-16 08:56 UTC
https://github.com/web-platform-tests/wpt-metadata/pull/160 associated a bug with Firefox instead of Safari.

Steps to reproduce:
1. Start at https://wpt.fyi/results/css/css-images?label=experimental&label=master&aligned
2. Edit the browsers shown to delete Edge, then copy the permalink and follow it
3. You will be at https://wpt.fyi/results/css/css-images?run_id=488890002&run_id=483120004&run_id=505970001
4. Click any cell with failures in the 3rd (Safari) column

You will see something like this:
![image](https://user-images.githubusercontent.com/498917/79435882-8173da80-7fd0-11ea-8780-28539cbb96ec.png)

Note the Firefox icon here instead of Safari.

It seems like there's some hardcoded mapping from column to browser that doesn't care about what the actual order is. Swapping the order illustrates this problem clearly, try https://wpt.fyi/results/css/css-images?run_id=483120004&run_id=505970001&run_id=488890002 and note that the first column is treated as Chrome, second is Edge, third is Firefox. In this example, all are wrong.

**Comment by stephenmcgruer** [comment] 2020-04-16 10:59
cc @Hexcles 

> It seems like there's some hardcoded mapping from column to browser that doesn't care about what the actual order is.

I doubt that is true. It's more likely that this is polymer data binding going wrong - I wouldn't be surprised if the metadata component binds to the first array of `products` and isn't updated if that changes.

> https://wpt.fyi/results/css/css-images?run_id=483120004&run_id=505970001&run_id=488890002 

This one is interesting, but https://wpt.fyi/results/css/css-images?label=master&product=firefox&product=safari&product=chrome has the correct browsers in the correct columns when triaging, which implies there is no such hard-coded order.

**Comment by KyleJu** [comment] 2020-04-16 14:47
I believe @stephenmcgruer is correct. Even with https://wpt.fyi/results/css/css-images?label=master&product=firefox&product=safari&product=chrome, if you click on `edit` to edit the browsers, you will see a mismatch.

<img width="1286" alt="Screen Shot 2020-04-16 at 10 39 40 AM" src="https://user-images.githubusercontent.com/8611520/79469886-bb43e180-7fce-11ea-9aaf-b15656bbb662.png">

The problem is that the displayed browsers on the first row of the table don't have `products` array to indicate selected browsers, but `testRuns`. So there is a mismatch every time you specify `run_ids` or `product` parameters in the URL

**Comment by KyleJu** [comment] 2020-04-16 14:59
Also it does nothing when you try to delete a browser in edit, https://wpt.fyi/results/css/css-images?product=chrome&run_id=483120004&run_id=505970001&run_id=488890002

**Comment by KyleJu** [comment] 2020-06-22 14:59
See [discussions](https://github.com/web-platform-tests/wpt.fyi/pull/2007#issuecomment-646239787).  To solve this issue, some refactoring is needed. For now, edit and permalink would fail any queries using `max-count` or  `run_id`

**Comment by KyleJu** [comment] 2020-11-24 07:13
The original issue mentioned by @foolip has been fixed in https://github.com/web-platform-tests/wpt.fyi/pull/2007. I filed a [query builder issue](https://github.com/web-platform-tests/wpt.fyi/issues/2272) and will send it a fix there

**Closed by KyleJu** 2020-11-24 07:13 UTC
