### ISSUE TITLE
[Interop 2023] Focus areas are not entirely alphabetical

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3119] opened 2023-01-27 09:31 UTC
"Math Functions" comes before "Masking". I've doubled checked the rest and it looks alphabetical. Discovered by reviewing https://github.com/web-platform-tests/interop/pull/267.

**Comment by gsnedders** [comment] 2023-01-27 12:56
Dupe of #3116.

**Closed by gsnedders** 2023-01-27 12:56 UTC
