### ISSUE TITLE
./util/docker-dev/run.sh gives error: "sudo: no tty present and no askpass program specified"

### ISSUE THREAD

**Issue by smfr** [web-platform-tests/wpt.fyi#1591] opened 2019-10-29 00:39 UTC
On macOS 10.15, I get:

 51$ $ ./util/docker-dev/run.sh
[  2019-10-28 17:37:47  INFO  ]  Creating docker instance for dev server. Instance name: wptd-dev-instance
[  2019-10-28 17:37:47  WARN  ]  Found existing docker instance wptd-dev-instance. Remove?
Confirm (y/N): y
[  2019-10-28 17:37:48  INFO  ]  Stopping wptd-dev-instance...
wptd-dev-instance
[  2019-10-28 17:37:49  INFO  ]  wptd-dev-instance stopped.
[  2019-10-28 17:37:49  INFO  ]  Removing wptd-dev-instance...
wptd-dev-instance
[  2019-10-28 17:37:49  INFO  ]  wptd-dev-instance removed.
[  2019-10-28 17:37:49  INFO  ]  Starting docker instance wptd-dev-instance...
416826f8d40a7f2f121517c3242f4be0e82dc0d168dcbf87f0907684417e9c64
[  2019-10-28 17:37:50  INFO  ]  Setting up local user
groupadd: GID '20' already exists
[  2019-10-28 17:37:51  INFO  ]  Ensuring the home directory is owned by the user...
[  2019-10-28 17:37:52  INFO  ]  Instance wptd-dev-instance started.
[  2019-10-28 17:37:52  INFO  ]  Updating system/packages...
sudo apt-get -qq update
sudo: no tty present and no askpass program specified
make: *** [apt_update] Error 1
Makefile:185: recipe for target 'apt_update' failed

**Comment by smfr** [comment] 2019-10-29 00:50
Same issue happens on 10.14.

**Comment by Hexcles** [comment] 2019-10-29 01:05
> groupadd: GID '20' already exists

This is #250 and is no longer a fatal error (fixed by #775).

> sudo: no tty present and no askpass program specified

This is new. I'll try to reproduce. What kind of Docker setup do you have (sorry I haven't used Docker on macOS before)?

**Comment by smfr** [comment] 2019-10-29 01:54
Using the macOS Docker app (2.1.0.4) from https://download.docker.com/mac/stable/Docker.dmg

**Comment by stephenmcgruer** [comment] 2019-10-31 13:42
@Hexcles did you have success reproducing?

**Comment by grorg** [comment] 2019-10-31 18:33
I noticed this when building the docker image (probably the same setup as @smfr)

`debconf: delaying package configuration, since apt-utils is not installed`

**Comment by grorg** [comment] 2019-10-31 18:34
..which might explain why apt_update failed.

**Comment by Hexcles** [comment] 2019-10-31 22:06
Unfortunately, I cannot reproduce this on:

macOS 10.14.6
Docker Desktop 2.1.0.4 (39773)
Engine: 19.03.4
Machine: 0.16.2

Command was executed in Terminal.app.

> debconf: delaying package configuration, since apt-utils is not installed

This log message is a red herring. It shows on Linux, too.

**Comment by Hexcles** [comment] 2019-10-31 22:07
Hmm, actually there is one difference: my macOS UID & GID are larger than 1000.

Let me try to create a user with a small UID & GID.

**Comment by smfr** [comment] 2019-10-31 22:24
I was able to run the tests by not using Docker, and using 'virtualenv' instead. I had to pip uninstall/pip install virtualenv to get a more recent version. Also, you need to enable the Safari "Allow Remote Automation" option, and turn off sleep on the machine running the tests.

**Comment by Hexcles** [comment] 2019-10-31 22:32
@smfr I've identified the root cause and have sent a fix #1597 , which should be merged soon.

Meanwhile, I'm a little confused. Are you trying to run WPT tests, or are you trying to bring up a local dev environment for the dashboard ([wpt.fyi](https://wpt.fyi))? This is the repo for the latter, and you don't need the Docker image to run WPT. 

Regarding virtualenv (for WPT), we have just landed a change to clarify the instructions and covered pip/virtualenv. Please take a look at the updated version: https://github.com/web-platform-tests/wpt/blob/master/docs/running-tests/from-local-system.md Let me know if you have more questions!

**Comment by smfr** [comment] 2019-10-31 22:34
My minimal requirements are to run the tests. I don't think I need a local wpt.fyi (though it would be kinda sweet to overlay data from local Safari builds onto the data for STP and the other browsers).

Perhaps the docs could clarify the difference between setting up a wpy.fyi instance and just running the wpt tests. That wasn't a clear distinction to me.

**Comment by Hexcles** [comment] 2019-10-31 22:36
> Perhaps the docs could clarify the difference between setting up a wpt.fyi instance and just running the wpt tests. That wasn't a clear distinction to me.

Certainly! Do you still remember how you got to this repo instead of the wpt repo?

**Comment by smfr** [comment] 2019-10-31 22:37
wpt.fyi -> GitHub Source -> Readme

**Comment by Hexcles** [comment] 2019-10-31 22:39
> wpt.fyi -> GitHub Source -> Readme

Aha! That makes a lot of sense. We should link to [web-platform-tests.org](https://web-platform-tests.org) instead.

**Closed** 2019-10-31 22:53 UTC
