### ISSUE TITLE
Store results of web-platform-tests PRs and allow comparing to master

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#118] opened 2018-05-03 13:07 UTC
This would be part of a solution to https://github.com/w3c/web-platform-tests/issues/7475 that doesn't involve https://pulls.web-platform-tests.org/.

Doing https://github.com/w3c/web-platform-tests/issues/10503 first might make this simpler, but it isn't strictly required, we could also get results from Travis.

**Comment by zcorpan** [comment] 2018-05-15 10:33
This is blocked on #9874

**Comment by lukebjerring** [comment] 2018-07-31 13:46
Whether we should do this is up for debate, regarding Travis CI secrets. We are not able to pull from Travis CI after the results report has been produced, so would have to push from Travis CI. This requires basic HTTP authentication (see [API docs](https://github.com/web-platform-tests/wpt.fyi/tree/master/api#results-creation)).

IMHO, it's fine to have a Travis login and secret, and special-case it in the endpoint to be flagged as `untrusted` in case we need to do anything extra special later in the UI. Note, also, that we could additionally lock that login down, using say, [Travis IPs](https://docs.travis-ci.com/user/ip-addresses/).

I think there's a lot of value added having these runs in our dataset.

**Comment by lukebjerring** [comment] 2018-07-31 13:47
@Hexcles, I trust you to make the right decision ;)

**Comment by lukebjerring** [comment] 2018-10-31 17:23
This is now a dupe of the implementation-specific #707.

**Closed by lukebjerring** 2018-10-31 17:23 UTC
